version: "3.1"

services:

  db:
    container_name: database
    image: postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - ".env"
    volumes:
      - pgdata:/var/lib/postgresql/data/
    networks:
      - botnet


  django:
    container_name: djangoproject
    build:
      context: .
    command: gunicorn web.web.wsgi:application -b 0.0.0.0:8000 --reload
    ports:
      - 8000:8000
    networks:
      - botnet
    restart: always
    volumes:
      - .:/src
    env_file:
      - ".env"
    depends_on:
      - db

  vkbot:
    container_name: bot
    build:
      context: .
    volumes:
      - .:/src
    networks:
      - botnet
    restart: always
    command: python app.py
    env_file:
      - ".env"
    depends_on:
      - db
      - django

  nginx:
    build:
      context: ./nginx/
      dockerfile: Dockerfile
    networks:
      - botnet
    depends_on:
      - django
      - db
    ports:
      - "80:80"
    volumes:
      - ./static/:/static
    restart: always

networks:
  botnet:
    driver: bridge

volumes:
  pgdata:

# systemctl enable docker.service

