# Generated by Django 3.1.8 on 2021-11-28 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homeworks',
            options={'verbose_name': 'Домашнее задание', 'verbose_name_plural': 'Домашние задания'},
        ),
    ]
