# Generated by Django 3.1.8 on 2021-11-28 09:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0002_auto_20211128_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworks',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 11, 28, 16, 17, 19, 291607), verbose_name='Дата'),
            preserve_default=False,
        ),
    ]
